### ISSUE TITLE
Mac Type Selector

### ISSUE THREAD

**Issue by ermau** [xamarin/Xamarin.PropertyEditing#116]
- Core (#113)
 - Editor:
   - [ ] Design
   - [ ] Localized
   - Behavior:
     - [ ] Keyboard control
     - [ ] Accessibility
     - [ ] Selection
   - Theming:
     - [ ] Light themed
     - [ ] Dark themed
     - [ ] High contrast

**Comment by vancura** [comment]
Same here, what design do you need?

**Comment by ermau** [comment]
Please see the design doc.

**Comment by jamiedawsonyoung** [comment]
@ermau What design doc? and where? I've been looking all over for this. Can you provide a link pls 👍

**Comment by vancura** [comment]
![image](https://user-images.githubusercontent.com/4982/48778425-6fa3e000-ecd5-11e8-98ff-23b4b1b00cfd.png)

Thoughts?

**Comment by vancura** [comment]
Up and down cursor keys (used to navigate the `NSOutlineView` with all the types) need to work even when the focus is in the filter text field.
