### ISSUE TITLE
Mac Collection Editor

### ISSUE THREAD

**Issue by ermau** [xamarin/Xamarin.PropertyEditing#117]
- Core:
   - [ ] View Model
   - [ ] Tests
 - Editor:
   - Mac Type Selector (#116)
   - [ ] Design
   - [ ] Localized
   - Behavior:
     - [ ] Keyboard control
     - [ ] Accessibility
     - [ ] Selection
   - Theming:
     - [ ] Light themed
     - [ ] Dark themed
     - [ ] High contrast

**Comment by vancura** [comment]
Please, what's this exactly? How can I help here?

**Comment by ermau** [comment]
The design doc you were originally sent details this.
