### ISSUE TITLE
Type icon provider

### ISSUE THREAD

**Issue by ermau** [xamarin/Xamarin.PropertyEditing#118]
VS displays icons for the various control types, we need an API for requesting icons for selected objects.
![untitled](https://user-images.githubusercontent.com/156582/33683945-8ebcfb64-da9a-11e7-8828-0c190f412823.png)

**Comment by vancura** [comment]
What does exactly this icon mean? The VS looks like inspection icon (click, select something, then inspect), but I am not sure that's what it does.

**Comment by ermau** [comment]
I've clarified the description, this issue is for infrastructure, not a specific icon.
