### ISSUE TITLE
Resources Core

### ISSUE THREAD

**Issue by ermau** [xamarin/Xamarin.PropertyEditing#120]
Need a way to retrieve values for resources for preview purposes.

**Comment by bleroy** [comment]
Here's a summary of the outcome of our previous discussion on this topic, plus some additional considerations...

## Requirements

1. Need to be able to get a list of available resources
2. Need to be able to retrieve values of resources
3. Need to be able to add a new resource (specifying what source to add it to)

## Current API

Currently, we have a `Resource` class with just a name property, and an `IResourceProvider` that defines how to get resources for a given property info. That interface is currently not implemented.

## To do

1. [ ] Add `Resource<T>: Resource` with a `T Value`.
2. [ ] Add a `Source` property to `Resource`.
3. [ ] Add `async Task<Resource<T>> CreateResource<T>(string name, T value, string source)` to `IResourceProvider`.
4. [ ] Add a `ResourceProvider` property to `PropertyEditorPanel` (like there is an `EditorProvider` already).
5. [ ] Mock implementation of a resource provider, integration into standalone apps.
6. [ ] Integrate resource picking into property presenters.
7. [ ] Add "create resource" UI where relevant.
