### ISSUE TITLE
Windows custom expression

### ISSUE THREAD

**Issue by ermau** [xamarin/Xamarin.PropertyEditing#133]
- [x] Core - #132
 - [x] Design
 - [x] Localized
 - Behavior:
   - [x] Keyboard control
   - [x] Accessibility
   - [x] Selection
 - Theming:
   - [x] Light themed
   - [x] Dark themed
   - [ ] High contrast

**Comment by vancura** [comment]
This doesn't need design?

**Comment by ermau** [comment]
@vancura No, it already exists in VS.
