### ISSUE TITLE
Mac custom expression

### ISSUE THREAD

**Issue by ermau** [xamarin/Xamarin.PropertyEditing#134]
- Core - #132
 - [x] Design
 - [ ] Localized
 - Behavior:
   - [ ] Keyboard control
   - [ ] Accessibility
   - [ ] Selection
 - Theming:
   - [x] Light themed
   - [x] Dark themed
   - [x] High contrast

**Comment by vancura** [comment]
<img width="422" alt="mac standard 2x" src="https://user-images.githubusercontent.com/4982/35572034-03fe0954-05d4-11e8-8ef7-384fcf531ad4.png">

<img width="502" alt="mac property button menu 2x" src="https://user-images.githubusercontent.com/4982/35572040-073d67f4-05d4-11e8-9e08-9dc6d999a0ea.png">

<img width="464" alt="mac property input 2x" src="https://user-images.githubusercontent.com/4982/35572053-09eff14c-05d4-11e8-89d4-fc76d738c774.png">
