### ISSUE TITLE
Windows Material color selector

### ISSUE THREAD

**Issue by ermau** [xamarin/Xamarin.PropertyEditing#136]
- [x] Design
  - I think the most logical thing here is to place it as another "color type" tab:
![image](https://user-images.githubusercontent.com/156582/35292688-4c76d570-003f-11e8-8f76-d5f9dbcc9b71.png)

 - [ ] Localized
 - Behavior:
   - [ ] Keyboard control
   - [ ] Accessibility
   - [ ] Selection
 - Theming:
   - [ ] Light themed
   - [ ] Dark themed
   - [ ] High contrast

**Comment by vancura** [comment]
## Inactive state

Nothing is selected.

<img width="408" alt="win android material color inline palette 2x" src="https://user-images.githubusercontent.com/4982/35618690-f9cbf6b4-067b-11e8-97fa-fdf5a60a88a3.png">

## Active Material Editor

<img width="408" alt="win android material color inline palette 2x" src="https://user-images.githubusercontent.com/4982/35618725-160918e8-067c-11e8-881b-abfb8075388e.png">

## Dark inactive state

<img width="408" alt="win android material color inline palette _dark 2x" src="https://user-images.githubusercontent.com/4982/35618774-3ac065ce-067c-11e8-9f25-d01fd60b4db8.png">

## Dark active state

<img width="408" alt="win android material color inline palette _dark 2x" src="https://user-images.githubusercontent.com/4982/35618811-5106ccba-067c-11e8-9b35-a85ac809373f.png">

Thoughts?
