### ISSUE TITLE
Mac Brush Editor

### ISSUE THREAD

**Issue by ermau** [xamarin/Xamarin.PropertyEditing#137]
Depends on #97 

 - [x] Core
 - Editor:
   - [x] Design
     - [x] Material color selector
   - [ ] Localized
   - Behavior:
     - [ ] Keyboard control
     - [ ] Accessibility
     - [ ] Selection
   - Theming:
     - [ ] Light themed
     - [ ] Dark themed
     - [ ] High contrast
   - States:
     - [ ] Error state
     - [ ] Bound state
     - [ ] Conflict state
     - [ ] Pending state

**Comment by vancura** [comment]
## Simple color picker

Simple color picker is used only when no special features are needed, i.e., for quick selection of colors.

<img width="408" alt="mac single color popup i 2x" src="https://user-images.githubusercontent.com/4982/35397546-0eebd91e-01f0-11e8-80ad-ad714c9bf110.png">

It would be good to have a few new features:

* bottom row with recently used colors,
* (...) icon to show the system color picker.

These features are also used in the more advanced color picker below.


## Color menu

A similar approach to Xcode has:

<img width="408" alt="mac single color popup ii 2x 1" src="https://user-images.githubusercontent.com/4982/35399227-120a2b56-01f4-11e8-9781-1eb78e304849.png">

Here we show a list of named colors, and a list of recently used colors, similar to the simple color picker above. The _Other..._ menu item opens the system color picker.


## Android Material Design color picker

<img width="549" alt="color selectors 2x 1" src="https://user-images.githubusercontent.com/4982/35397760-948f1cfc-01f0-11e8-9187-dcaa202a6992.png">

## Grouped colors color picker

### No properties selected

This is the usual state of the property pad – no properties are selected, hence the color picker is visible but disabled. Optionally we can hide it until there's a need for it. This is the disabled/semitransparent state (opacity = 33%).

<img width="408" alt="mac inline grouped colors none selected 2x" src="https://user-images.githubusercontent.com/4982/35398558-7fcf4d4e-01f2-11e8-85f2-3afb38795058.png">

### A color property is selected

The advanced color picker gets enabled, and it's possible to pick the color. The currently selected property row is blue with white text and icons (standard Apple treatment). The rest of color properties from the group are slightly blue (#D8E2F3) to show that they belong to the same group as the currently selected property.

Color picker toolbar contains two primary view buttons:

* Editor (color picker),
* Color Resources (a list of color resources).

The secondary toolbar contains brush switches:

* none,
* solid,
* gradient,
* image,
* resource.

These brushes are apparently not used on iOS (this mockup displays iOS Designer properties), but they need to be designed. Gradient, image and resource pickers will be designed later in this issue.

<img width="408" alt="mac inline grouped colors 2x" src="https://user-images.githubusercontent.com/4982/35398729-ee057b1c-01f2-11e8-80e3-6c1a29021978.png">

### List of color resources

Here we display a list of color resources (or resources in general), if available.

<img width="408" alt="mac inline grouped resources 2x 1" src="https://user-images.githubusercontent.com/4982/35399264-2848781e-01f4-11e8-968c-7219547aef7f.png">

**Comment by ermau** [comment]
@vancura a few questions:

 1. Are the recent colors/most used meant to be in the current session or over multiple sessions?
 1. The Material picker doesn't seem integrated, just off on its own. Does it make sense to have this as one of the brush switches?
 1. The drop down when not in a grouped state is just a list of color names, how do we get to the brush switcher from this point?

> This is the usual state of the property pad – no properties are selected, hence the color picker is visible but disabled. Optionally we can hide it until there's a need for it. This is the disabled/semitransparent state (opacity = 33%).

A third option is to just always have a property in the group selected so it never has a reason to hide/go transparent. It seems unlikely that people will unselect the property once they're done with it. This or going semitransparent is fine with me.

**Comment by bleroy** [comment]
@ermau Material is not so much a separate brush type as it is a different way to pick a color. Maybe we should have a way in the editor API to specify preferences in input methods (and potentially not just for colors). I would expect that when working on an Android project, I would be presented with Material front and foremost, with the current color picker as an "advanced" option, whereas a WPF project would put the current one first. We could get a coarse way of doing that with different types coming into the editor, but that could make for a confusing API, or we could have a more generic configuration API. That's probably a separate discussion to have.

@vancura one thing that is relatively hidden in the Windows solid color editor is the drop-down when you click on one of the color component labels, that gives you access to HSL, HSB, CYMK spaces in addition to the RGB one. On the mac, we have the opportunity to give that a better and more discoverable UI.

Another thing that's missing in the above design is the color space UI.

**Comment by ermau** [comment]
> Material is not so much a separate brush type as it is a different way to pick a color.

True, but that's not the only way to look at it. The selectors are simply different ways of manipulating the brush, Material is just another way. As presented above it's as though it's an entirely different property type, which shouldn't be the case.

> Maybe we should have a way in the editor API to specify preferences in input methods (and potentially not just for colors). I would expect that when working on an Android project, I would be presented with Material front and foremost, with the current color picker as an "advanced" option, whereas a WPF project would put the current one first. We could get a coarse way of doing that with different types coming into the editor, but that could make for a confusing API, or we could have a more generic configuration API.

This is all tangential; We will show the material picker only on android and in an appropriate place. We only need to figure out where that is.

**Comment by bleroy** [comment]
And we also need to figure out how the client code is going to tell the property panel that it is Android, but yes, tangential.

**Comment by vancura** [comment]
> Are the recent colors/most used meant to be in the current session or over multiple sessions?

Good question, @ermau. It needs to be saved, that's for sure. But is it meant to be a system-wide recent list, across all projects, or let's say a color palette per a project? It's more a thing of implementation, and both ways would be good. But we definitely need to save it for the next launch. There would be no reason for the recent list if it were wiped on every VSMac/VS/whatever launch.

> The Material picker doesn't seem integrated, just off on its own. Does it make sense to have this as one of the brush switches?

Android Designer has these three buttons:

<img width="674" alt="screen shot 2018-01-26 at 16 10 52" src="https://user-images.githubusercontent.com/4982/35445970-95e32a9e-02b3-11e8-8b7f-dace79a08625.png">

1. the (...) button is the Resource Browser,
* the square is a standard color picker,
* the palette button shows this Android Material palette popover.

So basically you have two ways of selecting the color (not talking about Resource Browser which is pretty standard).

I thought we could use a similar principle, a color box similar to what iOS has and a secondary button for the Material palette popover. I'll design both now.

The inline Material palette, similar to the inline color picker, makes total sense and I'll draw it too.

> The drop down when not in a grouped state is just a list of color names, how do we get to the brush switcher from this point?

I thought you'd click the _Editor_ toolbar button. Then you'd get back to the toolbar without filter textfield, but with the secondary switcher. That would work for solid colors only, but is there a chance we'd display a list of images, gradients and resources in the list too (where it's possible, UWP/WPF)?

> A third option is to just always have a property in the group selected so it never has a reason to hide/go transparent. It seems unlikely that people will unselect the property once they're done with it. This or going semitransparent is fine with me.

That would be confusing, I am afraid. I thought the selected row/property is selected only when the user navigates there (via mouse or keyboard). An auto-selected property on start would be misleading.

> One thing that is relatively hidden in the Windows solid color editor is the drop-down when you click on one of the color component labels, that gives you access to HSL, HSB, CYMK spaces in addition to the RGB one. On the mac, we have the opportunity to give that a better and more discoverable UI. Another thing that's missing in the above design is the color space UI.

I'll design all of them now.

**Comment by vancura** [comment]
Update on inactive inline color picker (no color property from the grouped list is selected):

<img width="408" alt="mac inline grouped colors none selected 2x" src="https://user-images.githubusercontent.com/4982/35446899-6c645b18-02b6-11e8-9b78-b9dc8010ee07.png">

Selected rings are hidden, that's the only change. There's no reason to show them since they can't be selected or moved.

**Comment by vancura** [comment]
> So basically you have two ways of selecting the color (not talking about Resource Browser which is pretty standard). I thought we could use a similar principle, a color box similar to what iOS has and a secondary button for the Material palette popover. I'll design both now.

![3 2x](https://user-images.githubusercontent.com/4982/35447644-8862d7f2-02b8-11e8-8f26-2d35d6c3114c.gif)

**Comment by ermau** [comment]
> Good question, @ermau. It needs to be saved, that's for sure. But is it meant to be a system-wide recent list, across all projects, or let's say a color palette per a project? It's more a thing of implementation, and both ways would be good. But we definitely need to save it for the next launch. There would be no reason for the recent list if it were wiped on every VSMac/VS/whatever launch.

Ok, this sounds good, we're just going to have to punt on it for now. We can add it later.

> I thought you'd click the Editor toolbar button. Then you'd get back to the toolbar without filter textfield, but with the secondary switcher. That would work for solid colors only, but is there a chance we'd display a list of images, gradients and resources in the list too (where it's possible, UWP/WPF)?

The grouped version of the color property editor really shouldn't differ from the inline element. If the grouped shows access to images, gradients and resources, why wouldn't the inline one? WPF, Forms (via Inspector) and Android would all make use of this.

> That would be confusing, I am afraid. I thought the selected row/property is selected only when the user navigates there (via mouse or keyboard). An auto-selected property on start would be misleading.

Keep in mind that the groups of selectable properties aren't actually specific to colors, it's meant to be a reusable component (see #97 and "Gorup editor" in the doc). Can you elaborate on how this would be misleading?

**Comment by vancura** [comment]
> The grouped version of the color property editor really shouldn't differ from the inline element. If the grouped shows access to images, gradients and resources, why wouldn't the inline one? WPF, Forms (via Inspector) and Android would all make use of this.

You mean the popover version, right? :)

I am just afraid we shouldn't overuse the popover version. It's always bad when popovers are overflowing with features, it's a tricky widget, and difficult to control. That's my primary reason why I designed it slim.

> Can you elaborate on how this would be misleading?

Imagine you open Designer, select a widget on canvas and the immediatelly active property would be one of the colors. I think it's better to let the user select what they want to change, so we'd start with no property selected (while a widget from canvas is selected).

**Comment by ermau** [comment]
> You mean the popover version, right? :)
>I am just afraid we shouldn't overuse the popover version. It's always bad when popovers are overflowing with features, it's a tricky widget, and difficult to control. That's my primary reason why I designed it slim.

The choice isn't up to us though, that's why it's important that they not differ. The inline/popup version appears when we're in arrange by name mode. The grouped appears when they are in arrange by category.

**Comment by vancura** [comment]
> The inline Material palette, similar to the inline color picker, makes total sense and I'll draw it too.

Unselected state:

<img width="408" alt="mac android material color inline inactive 2x" src="https://user-images.githubusercontent.com/4982/35449124-609bb3c0-02bc-11e8-9c5b-5662c683257b.png">

Standard picker selected (see the changed toolbar, too):

<img width="408" alt="mac android material color inline 2x" src="https://user-images.githubusercontent.com/4982/35449165-86af2268-02bc-11e8-82a8-64e4d654f529.png">

Inline Material color palette:

<img width="408" alt="mac android material color inline palette 2x" src="https://user-images.githubusercontent.com/4982/35449134-6862b234-02bc-11e8-854c-ab93b57f5c1a.png">

**Comment by vancura** [comment]
> One thing that is relatively hidden in the Windows solid color editor is the drop-down when you click on one of the color component labels, that gives you access to HSL, HSB, CYMK spaces in addition to the RGB one. On the mac, we have the opportunity to give that a better and more discoverable UI.

What about this?

<img width="408" alt="mac inline grouped colors 2x" src="https://user-images.githubusercontent.com/4982/35449749-2d497a0a-02be-11e8-965a-49aa2c59a44a.png">

I don't want to hide it behind a menu of any sort since this whole picker needs to work in a popover too. Imagine showing a contextual menu out of a popover, that would be a massive UX fail, not talking about problems what popover/menu is active and how to handle them.

**Comment by ermau** [comment]
> What about this?

Perfect.

**Comment by bleroy** [comment]
The HSB/HSL/RGB/CMYK is great, thanks.

> I don't want to hide it behind a menu of any sort since this whole picker needs to work in a popover too. Imagine showing a contextual menu out of a popover, that would be a massive UX fail, not talking about problems what popover/menu is active and how to handle them.

And yet that is exactly what we have in Windows (although it doesn't have any more problems than your garden variety hierarchical menu). Should we consider improving on the VS design when it's clearly wrong?

**Comment by vancura** [comment]
> And yet that is exactly what we have in Windows (although it doesn't have any more problems than your garden variety hierarchical menu). Should we consider improving on the VS design when it's clearly wrong?

Yes, please. But case by case, to be honest, there's nearly everything that's bad in terms of UX in VS :)

**Comment by vancura** [comment]
## Inline No Brush Editor

<img width="408" alt="mac inline no brush editor 2x" src="https://user-images.githubusercontent.com/4982/35524574-41fabb56-0522-11e8-9b1a-1bea74ab2f74.png">


## Inline Gradient Brush Editor

<img width="408" alt="mac inline gradient brush editor 2x" src="https://user-images.githubusercontent.com/4982/35524585-48d42b06-0522-11e8-83ee-09b5738296d8.png">


## Dark theme

<img width="408" alt="mac inline grouped colors _dark 2x" src="https://user-images.githubusercontent.com/4982/35524589-4d6f2aa8-0522-11e8-80aa-c5d358c2b6ce.png">


Thoughts?

**Comment by ermau** [comment]
@vancura we can probably just hide editor/color resources on "no brush", but 👍

**Comment by vancura** [comment]
@ermau Updated: https://github.com/xamarin/Xamarin.PropertyEditing/issues/137#issuecomment-361321486

**Comment by vancura** [comment]
Dark themes of what makes sense to design:

<img width="408" alt="mac inline grouped colors dark 2x" src="https://user-images.githubusercontent.com/4982/35578371-2cb90460-05e4-11e8-8966-9281129e5e1b.png">

<img width="408" alt="mac inline grouped resources dark 2x" src="https://user-images.githubusercontent.com/4982/35578378-304019b6-05e4-11e8-901d-9194c70a649d.png">

<img width="408" alt="mac android material color inline palette _dark 2x" src="https://user-images.githubusercontent.com/4982/35578385-34df78cc-05e4-11e8-9f2a-c472f903c5f2.png">

<img width="408" alt="mac inline gradient brush editor _dark 2x" src="https://user-images.githubusercontent.com/4982/35578391-37c6de68-05e4-11e8-9077-74b8b6778152.png">

**Comment by lewing** [comment]
@vancura remind me where I can get the icon assets and possibly the paths for the gradient tabs

**Comment by vancura** [comment]
@lewing The icons are at https://github.com/xamarin/icons/tree/master/property-pad ([Figma source](https://www.figma.com/file/HPUW1fWYrLKlj7iV1EIAmX/Property-Pad) if you need it). But what paths do you mean?

**Comment by lewing** [comment]
@vancura I was thinking of 
![image](https://user-images.githubusercontent.com/24063/42651550-538146a4-85d5-11e8-8d4a-a6f209510c14.png) when I asked.  Not exactly complicated to reproduce just checking if I could extract them.

**Comment by vancura** [comment]
You'll need to extract that from Figma, or I can render two images for you: one for masking the color, and the second one with a stroke to overlay over it. Although I think it would be safer to render that with code, I might be wrong. So, images?
