### ISSUE TITLE
Windows combinable predefined value editor

### ISSUE THREAD

**Issue by ermau** [xamarin/Xamarin.PropertyEditing#166]
There are no existing VS designs for this, it's effectively a series of values that can toggled on and off non-exclusively.

 - [x] Core
 - Editor:
   - [ ] Design
   - [ ] Localized
   - Behavior:
     - [ ] Keyboard control
     - [ ] Accessibility
     - [ ] Selection
   - Theming:
     - [x] Light themed
     - [x] Dark themed
     - [ ] High contrast
   - States:
     - [ ] Error state
     - [ ] Bound state
     - [ ] Conflict state
     - [ ] Pending state

**Comment by vancura** [comment]
Thoughts?

<img width="408" alt="groups and separators win 2x" src="https://user-images.githubusercontent.com/4982/35915740-50e9cd5e-0c08-11e8-8bf1-456125069b01.png">

**Comment by alanmcgovern** [comment]
It looks like this is the same setup as the iOS designer currently has - a flat list of checkboxes which can be checked/unchecked in order to generate the final value. It seems reasonable enough to me.

I don't think anything in that screenshot is a combinable enum, but https://developer.apple.com/documentation/uikit/uiviewautoresizing is and it could be represented in this way with 6 checkboxes.

**Comment by ermau** [comment]
@vancura I'm not really sure how any of this maps. Are all these checkboxes for the one property of "Indicators" ? We don't have any subcategories for them and what would the dropdown show? Additionally I'm concerned what this might look like for some enum that has 20 flag options.

https://developer.android.com/reference/android/view/View.html#attr_android:scrollIndicators is another example.

**Comment by BretJohnson** [comment]
Here's the Android Studio UI for scrollIndicators:

![image](https://user-images.githubusercontent.com/245892/35930328-9d1b737a-0bff-11e8-9d16-ac6dcf6e25b5.png)

**Comment by vancura** [comment]
What do you think about this?

<img width="408" alt="groups and separators win 2x" src="https://user-images.githubusercontent.com/4982/35972063-963078a4-0cd0-11e8-9b3b-8efb1a6eb026.png">

**Comment by alanmcgovern** [comment]
I'm not sure the label like construct makes sense as a general solution.

For vertical/horizontal scroll indicators the property name is `showsHorizontalScrollIndicator` and `showsVerticalScrollIndicator`.There's no way for us to show `Horizontal` and `Vertical` labels unless we hardcode that short name in addition to the label and actual property value.

The same is true for the bounce related properties.

While we could go through all of our properties and hardcode short names, we could not do so for every property in the .NET framework. For the case where there are 20+ enum values (like eric mentioned) there would also be little to no benefit from those labels as it would either linewrap and take up several lines to show all the information, or it would truncate and be useless as an overview.

**Comment by CartBlanche** [comment]
@alanmcgovern but it would be fine to show the full combinable flag name right? so you can see at a glance, before expanding, what is already selected?

**Comment by alanmcgovern** [comment]
My point is that the 'fully combined flag name' is very long and *won't* be readable at a glance :)

**Comment by alanmcgovern** [comment]
Assuming that these options are all mutually exclusive, I'd consider `Top|Bottom|Left|Right|Start|End` to be unreadable :P

**Comment by CartBlanche** [comment]
Really?? it seems quite clear that | is the delimiter (or if we used a command to make it more language like, just as we easily read code with a { and know that is a delimiter. We are dealing with devs after all and not luddites :) 

So do we auto-expand by default?

**Comment by CartBlanche** [comment]
And with better spacing.... 

> Top | Bottom | Left | Right | Start | End

**Comment by alanmcgovern** [comment]
Which brings us back to the 'truncate or wrap' comment. This shorthand isn't actually making it *easier* to see what's set even in this simple case, so i'm questioning the benefit of the shorthand.

**Comment by CartBlanche** [comment]
As each platform is supposed to stick to certain naming conventions for its flags/enums, can we not come up with an algo to parse them to get the shorthand version, without resorting to hand coding them?

**Comment by BretJohnson** [comment]
@vancura - Here's a screenshot of the current Proppy Windows UI for combinable properties, that Eric added. It looks pretty good, I think. Do you suggest any changes there, for 15.7?

![image](https://user-images.githubusercontent.com/245892/36560585-2359bf6a-17df-11e8-8576-429bb2069ca3.png)

**Comment by vancura** [comment]
It looks really good. I'd just top-align the headline (_Foreground Gravity_), imagine a long list you would need to scroll to see fully. I think it should be top-aligned.

That gave me an idea, I'd love this:

![test](https://user-images.githubusercontent.com/4982/36595285-de867356-18a1-11e8-9c33-d3c3974c6a21.gif)

Basically, that the label would scroll normally until the whole property is cut from the top (top position is negative), then it would stick to the top of the scroll area. Similar to how iOS handles tables.

Thoughts?

**Comment by ermau** [comment]
I like the idea of that, but it's more of a nice to have so I'll break it out into another issue so I can finalize this one.
