### ISSUE TITLE
VS theming integration

### ISSUE THREAD

**Issue by ermau** [xamarin/Xamarin.PropertyEditing#185]

**Comment by BretJohnson** [comment]
This is done except for Eric providing correct mappings for the 21 or so commented out brushes in `designer\Xamarin.Designer.VisualStudio\src\VisualStudio.Designer\VisualStudioPropertyPanelTheme.cs` (`android-proppy-fixes` branch), mapping to public VS brushes or Cider brushes, or perhaps making some other change for those brushes, as appropriate.
