### ISSUE TITLE
Editor context button

### ISSUE THREAD

**Issue by ermau** [xamarin/Xamarin.PropertyEditing#19]
![image](https://cloud.githubusercontent.com/assets/156582/26323059/6e031f60-3efb-11e7-891e-6db7c5db9b33.png)

- [x] Windows
- Mac
  - [x] Design
  - [x] Implementation

**Comment by dvdsgl** [comment]
How do I access this menu?

**Comment by ermau** [comment]
@dvdsgl The square button next to any WPF/UWP property in VS.

**Comment by CartBlanche** [comment]
As per spec.
<img width="728" alt="screen shot 2018-02-14 at 11 15 40" src="https://user-images.githubusercontent.com/271363/36201641-82e890e0-1178-11e8-8907-c3cb0c425439.png">

Part of https://github.com/xamarin/Xamarin.PropertyEditing/pull/143
