### ISSUE TITLE
Windows solid brush editor

### ISSUE THREAD

**Issue by ermau** [xamarin/Xamarin.PropertyEditing#20]
![image](https://cloud.githubusercontent.com/assets/156582/26322026/3e6aa2d6-3ef7-11e7-9cdf-17d4d019cbdf.png)

Depends on #15 

- Solid Color Editor
  - [x] Color Picker
  - [x] RGBA Editors
  - [x] Hex editor
  - [x] Initial Color
  - [x] Current Color
  - [x] Last Color
  - [ ] Eyedropper
  - [ ] Resource picker
- [x] Grouped property picker (#98)
- [x] Brush type selector

![image](https://cloud.githubusercontent.com/assets/156582/26370811/f4e1cc04-3fc6-11e7-9eaf-10499d4aa63a.png)

**Comment by dvdsgl** [comment]
What are some competitive examples here? Who has the best implementation? Can we copy it?
