### ISSUE TITLE
Scrolling with category view is jerky

### ISSUE THREAD

**Issue by BretJohnson** [xamarin/Xamarin.PropertyEditing#218]
In the proppy UI, switch to category view, either for the VS Android UI or standalone.  Expand a couple of categories and then scroll.

Result:  The scrolling is "jerky", only allowing scrolling to positions where a category header is at the top.
It feels pretty unnatural and non-standard.

I presume there's some technical reason it's currently like this but IMO we should fix it for 15.7, though not necessarily for 1st preview release.

**Comment by ermau** [comment]
I think there's a scrolling mode that controls this that we can change. Need to look into its implications for virtualization.

**Comment by CartBlanche** [comment]
OK
