### ISSUE TITLE
Square icon for resource based properties is yellow, not green, in VS

### ISSUE THREAD

**Issue by BretJohnson** [xamarin/Xamarin.PropertyEditing#254]
Using the property editor for Android (VS integration), set any property from a resource.
Note that square icon on the right changes to yellow, not the expected green that shows on the popup menu.
This could be a color mapping issue.

![image](https://user-images.githubusercontent.com/245892/37475322-cfa0710a-2848-11e8-923a-7377c1c77fce.png)

**Comment by garuma** [comment]
I guess there was no predefined Cider color for that case so I defaulted it to the same as Databinding until we figure out what the right color should be.

Modify away in https://github.com/xamarin/designer/blob/master/Xamarin.Designer.VisualStudio/src/VisualStudio.Designer/Resources/ProppyColors.xaml#L6-L7
