### ISSUE TITLE
SetValueAsync is called even when value hasn't changed, resetting to Local

### ISSUE THREAD

**Issue by BretJohnson** [xamarin/Xamarin.PropertyEditing#255]
For editbox based properties (and probably others), it looks like `IObjectEditor.SetValueAsync` is called whenever the edit control gains focus and when it loses focus, even if the user hasn't changed anything. The `ValueInfo.Source` in this case is always Local, even it wasn't previously Local.

I would think `SetValueAsync` should only be called if the value has actually changed, say by proppy comparing the old value and new.

Often the effects here are benign, if a little inefficient, but in some scenarios it causes a bug:

- In the Android property editor, pick an integer property, like say `Accessibility Traversal After` for a Button widget.
- Bring up the resource picker and set the value from a resource.
- Note that the square icon on the right indicates its a resource based property.
- Click somewhere else, to change focus
- Note that the property changes to Local (square is white).

**Comment by ermau** [comment]
Ok so the reason that this happens is a couple things:

 - At the bottom most level the equivalency check is comparing value and value source. At the bottom value, this is correct. You can have the same value when you change local -> resource or resource -> local, but you need to actually commit the change in source.
 - The Value property sets the value to a local source when it is called.
 - The Windows binding automatically pushes the binding on focus leave regardless of change.

We probably need to define that property as for direct user input only. In that case we could do value-only check first and then move on to the normal behavior. Other mechanisms (like a conversion command) would use the base level value setting methods.
