### ISSUE TITLE
Brush editor popup is not properly placed

### ISSUE THREAD

**Issue by garuma** [xamarin/Xamarin.PropertyEditing#262]
![screen shot 2018-03-22 at 11 12 15 am](https://user-images.githubusercontent.com/104105/37779342-921f92e6-2dc2-11e8-9415-f7bd50903010.png)

I'm assuming it's supposed to pop under the "no brush" zone in the screenshot.

**Comment by ermau** [comment]
No, it's meant to be left aligned.

**Comment by bleroy** [comment]
That's what I thought as well, but I double-checked the VS behavior, and it's aligned on the right  of the preview box:
![image](https://user-images.githubusercontent.com/1165609/37780305-b97f49c4-2dab-11e8-91e2-1a9b1f4960bf.png)

**Comment by ermau** [comment]
> That's what I thought as well, but I double-checked the VS behavior

Are you sure? I just checked it and it's left aligned.

![image](https://user-images.githubusercontent.com/156582/37781597-60f84e9c-2dc7-11e8-908a-e8e1ce83fcdc.png)

**Comment by ermau** [comment]
> Does that make sense? With the animation it has it seems to pop out of nowhere, it also means you have to move your mouse away from the trigger zone if you want to start setting things.

We started by copying the VS behavior, and I'd argue the likelihood of having the panel so wide is probably not that high. That said I don't think it would be the worst thing if it left aligned to the color box instead.

**Comment by garuma** [comment]
We don't have the pointer in @bleroy screenshot but could it be that it takes that into account when determining the position to pop from? That would make sense as well.

**Comment by ermau** [comment]
Nope:
![image](https://user-images.githubusercontent.com/156582/37782217-bea587fc-2dc8-11e8-8ae9-b2b2b8750027.png)
but that also is a good option.

**Comment by bleroy** [comment]
> We don't have the pointer in @bleroy screenshot but could it be that it takes that into account when determining the position to pop from? That would make sense as well.

Yeah, I tested that as well. Doesn't make a difference. Positioning of the panel on the screen also has no effect as long as it doesn't bleed out.
