### ISSUE TITLE
Binding error on 'LightForegroundThreshold' on material design tint change

### ISSUE THREAD

**Issue by ermau** [xamarin/Xamarin.PropertyEditing#320]
System.Windows.ResourceDictionary Warning: 9 : Resource not found; ResourceKey='MaterialDesignColorControlItem'

**Comment by bleroy** [comment]
Couldn't repro the original resource warning, but this happens on changing the MD tint:

`System.Windows.Data Error: 4 : Cannot find source for binding with reference 'RelativeSource FindAncestor, AncestorType='Xamarin.PropertyEditing.Windows.ChoiceControl', AncestorLevel='1''. BindingExpression:Path=DataContext.NormalColorScriptureLightnessThreshold; DataItem=null; target element is 'BrushBoxControl' (Name=''); target property is 'LightForegroundThreshold' (type 'Double')`
