### ISSUE TITLE
Mac solid color editor inconsistently formats components

### ISSUE THREAD

**Issue by bleroy** [xamarin/Xamarin.PropertyEditing#347]
Components that are percentages, such as saturation, are displayed as decimal values between 0 and 1. On Windows, they are displayed as rounded percentages (including the % sign), and switch to a rounded decimal between 0 and 100 with one digit after the decimal point. Hue is similarly rounded differently: integer with a degree symbol when unfocused, decimal with one digit after the decimal point when focused.

**Comment by lewing** [comment]
The mac designs didn't cover these cases so I just followed the property types. The to/from on the color value is very easy to fix. It is not clear the current NumericSpinEditor control (NSTextField+NSStepper) can deal with unit format strings.

**Comment by bleroy** [comment]
Do we think there's value in using the spin control in this context?
