### ISSUE TITLE
[Mac] Brush Alignment Tweaks

### ISSUE THREAD

**Issue by CartBlanche** [xamarin/Xamarin.PropertyEditing#359]
As suggested from @vancura.
- [x] Not centered:

<img width="76" alt="image 2018-08-01 at 11 31 38 am" src="https://user-images.githubusercontent.com/4982/48713413-816f7f80-ec10-11e8-805b-641ad6395656.png">

- [x] Change RowHeight to be consistent with other ListViews
- [x] Column Width cuts off text

**Comment by CartBlanche** [comment]
Changes happening on this branch....

https://github.com/xamarin/Xamarin.PropertyEditing/tree/dominique-BrushTweaks

**Comment by CartBlanche** [comment]
@vancura The links you had no longer work. Do you have a new site?

**Comment by vancura** [comment]
Sorry, ticket description updated.

**Comment by CartBlanche** [comment]
Thanks!

**Comment by CartBlanche** [comment]
Mored the Resource alignment item to its own issue ( #458 ), as it was taaking an inordinate amount of time to find a fix.
