### ISSUE TITLE
Basic autocomplete core

### ISSUE THREAD

**Issue by ermau** [xamarin/Xamarin.PropertyEditing#375]
There's two tiers of autocomplete we can support. One is a simple replacement for things like resource names as Android has today, and the other is closer to what you'd expect out of an IDE for things like markup extensions. This is the issue for the former, the later will live in #307 

![image](https://user-images.githubusercontent.com/156582/40138566-17703602-591b-11e8-9b82-8cb1608c9d09.png)

**Comment by CartBlanche** [comment]
Should this issue be closed, shouldn't it stay open until the Mac side is completed?
