### ISSUE TITLE
Value input mode Windows

### ISSUE THREAD

**Issue by ermau** [xamarin/Xamarin.PropertyEditing#383]
Windows implementation of #382 

Existing design:
![image](https://user-images.githubusercontent.com/156582/46026621-d633c580-c0b9-11e8-8531-96a87505ce2e.png)

**Comment by jamiedawsonyoung** [comment]
@ermau is there a spec for this? Hylke will work on this next week but it's a little vague at the moment what you're after? (is it just the whole dialog above?) or just the right side?

**Comment by ermau** [comment]
@jamiedawsonyoung It's the editor that the drop down is open for in the image. A demonstration can be see in the gif from the PR:

![2018-09-28_13-58-07](https://user-images.githubusercontent.com/156582/46229340-544ed100-c333-11e8-8f27-1d96bc66dde9.gif)

Essentially, it's just an selector for determining what type of input is being entered into a text box. We've matched what VS does here for WPF's sizes for rows/colums in `Grid`. The existing Android version of this on mac looks like this (where the input mode is selecting between dimen/ems/lines):

![image](https://user-images.githubusercontent.com/156582/48575529-3687fc00-e8e0-11e8-97c8-6400c3a5f2d0.png)

**Comment by hbons** [comment]
Can you please describe what needs to be done. :)

**Comment by alanmcgovern** [comment]
@vancura Can you fill @hbons in if you have prior knowledge here?

**Comment by vancura** [comment]
I think there was some confusion about who's going to do what – I thought the request was the window itself, which is here: https://github.com/xamarin/Xamarin.PropertyEditing/issues/117. @hbons, could you please take a look at the dialog instead and leave this one to me?

**Comment by jamiedawsonyoung** [comment]
@alanmcgovern would you mind clearing this up as the image at the top suggests one thing and the message from @ermau suggest is a smaller thing? Much appreciated!

**Comment by jamiedawsonyoung** [comment]
@vancura Can you hang fire until @alanmcgovern lets us know what they need 👍

**Comment by vancura** [comment]
Thoughts? 

![tmp 2x](https://user-images.githubusercontent.com/4982/49447384-aea65b00-f7d6-11e8-9074-a6a08aab365e.png)

**Comment by jamiedawsonyoung** [comment]
Hey @vancura I was chatting with @alanmcgovern yesterday and we agreed that we should keep all the conversations and interactions inside Azure DevOps for now, even if there are corresponding issues in GitHub. The more channels we open for conversations on a thing, the more chance we have of missing/miscommunication. That make sense? If we want to we can totally update this issue once it's resolved.

**Comment by vancura** [comment]
Design and talk at https://devdiv-design.visualstudio.com/D3%20Studio/_workitems/edit/3448.

**Comment by hbons** [comment]
What's needed from me? 😊
________________________________

**Comment by vancura** [comment]
@hbons: Nothing :)
