### ISSUE TITLE
[Mac] CommonBrushView appears to be lazy loading its view, which causes flicker

### ISSUE THREAD

**Issue by CartBlanche** [xamarin/Xamarin.PropertyEditing#428]
Repro: 
Open Brush selector. 
Select Resource list
Type something in the filter search box.
Notice Flicker

> VS bug [#703874](https://devdiv.visualstudio.com/DevDiv/_workitems/edit/703874)

**Comment by AnBucyk** [comment]
Resolved as not repro. I think there may be a new bug blocking repro for this one. No flicker, but the color rectangles change size every time you type into the filter, making the color rectangles in the collection smaller and smaller. Will re-open upon fixing the other bug if it then repros.
