### ISSUE TITLE
[Mac] Brush preview and text need to move up 1 or 2 pixels...

### ISSUE THREAD

**Issue by CartBlanche** [xamarin/Xamarin.PropertyEditing#431]
Please refer to screenshot below...

<img width="689" alt="screen shot 2018-10-10 at 13 37 20" src="https://user-images.githubusercontent.com/271363/46755092-3584fe80-cc92-11e8-8ea0-6971d13bafbb.png">

> VS bug [#703873](https://devdiv.visualstudio.com/DevDiv/_workitems/edit/703873)

**Comment by bleroy** [comment]
Fixed in current build: 
<img width="315" alt="image" src="https://user-images.githubusercontent.com/1165609/55647878-a74a8a80-5793-11e9-88bb-9d0b3d836457.png">
