### ISSUE TITLE
[Mac] When integrated in VS for mac, the property panel doesn't entirely capture focus

### ISSUE THREAD

**Issue by bleroy** [xamarin/Xamarin.PropertyEditing#437]
Repro:
In VSM, running an extension that uses the property panel, load an editor that brings up the panel, then select an item and focus on one of the property editors.

Expected: the property panel's property editor has focus exclusively.
Actual: Typing text results in it appearing in the property panel and in the previously focused pad.

Note: this happens when the previously focused pad uses a different UI toolkit from the property panel.

> VS bug [#707111](https://devdiv.visualstudio.com/DevDiv/_workitems/edit/707111)

**Comment by xamarin-release-manager** [comment]
> [sync] [VS-17] Comment by **xamarinc**



Fixed in version 4.18.0.902 (master)



Author: Alan McGovern  
 Commit: 46840a2de4e1c344b40ec3fa426f2acd5c611d02 (xamarin/designer)
