### ISSUE TITLE
[Mac] Constraints probably broken when collapse/expand brush category content

### ISSUE THREAD

**Issue by netonjm** [xamarin/Xamarin.PropertyEditing#455]
The problem happens in current master branch with the example project in Mac platform:

1) Open example
2) Select arrangle by Category
3) Expand Brush category/collapse

expected: sections collapses
result: all views disapear

**Comment by CartBlanche** [comment]
@netonjm I'm not seeing this behaviour in latest master.
Brush expanded....
<img width="812" alt="screen shot 2018-12-03 at 11 51 19" src="https://user-images.githubusercontent.com/271363/49369505-d8d21d00-f6f1-11e8-9797-0e7ea0fbfbb0.png">

Brush expanded....
<img width="815" alt="screen shot 2018-12-03 at 11 51 32" src="https://user-images.githubusercontent.com/271363/49369506-d8d21d00-f6f1-11e8-8d52-3f19f3f707f8.png">

Is there a step I'm missing? If you are still seeing it, maybe a short video/gif showing the issue?

**Comment by ermau** [comment]
This all changed quite a bit with the theming changes. Re-open if it's still an issue with a demonstration please.
