### ISSUE TITLE
[Win] Collection editor should use a better string for the items

### ISSUE THREAD

**Issue by CartBlanche** [xamarin/Xamarin.PropertyEditing#456]
When using the collection editor we should use a better string for the items, one which better represents what each one is. In this scenario we could show the `1*` as this is a 1* row definition.

<img width="580" alt="screen shot 2018-11-21 at 12 37 55" src="https://user-images.githubusercontent.com/271363/48842385-059a4200-ed8c-11e8-9af4-bf29bc9bfe08.png">

**Comment by ermau** [comment]
These items and their properties therein are completely dynamic. We'd have to add hinting information APIs for the provider to tell us what to display here, as we have no way of inferring it ourselves.
