### ISSUE TITLE
Filter and Arrange header requires a lot of space

### ISSUE THREAD

**Issue by lewing** [xamarin/Xamarin.PropertyEditing#48]
The header that has the filter and Arrange controls doesn't handle narrow panels very well.  The poor layout actually causes functional problems because you can't operate the drop down from label.  You have to resize the window to expose the handle before it is possible to change the arrangement.

![image](https://user-images.githubusercontent.com/24063/30215294-2ee43bbe-9475-11e7-9a44-4874066b76da.png)

**Comment by lewing** [comment]
Any update on this? The Mac editor requires a large amount of horizontal space to work properly.

**Comment by ermau** [comment]
Fixed in 8008d53
