### ISSUE TITLE
The texts of the labels are cut into standard window sizes

### ISSUE THREAD

**Issue by netonjm** [xamarin/Xamarin.PropertyEditing#486]
![image](https://user-images.githubusercontent.com/1587480/50037499-54956900-0012-11e9-87b9-2704d3c6643c.png)

**Comment by CartBlanche** [comment]
As a temporary stop gap, would setting tooltips, like this help...
<img width="333" alt="screen shot 2019-02-11 at 09 50 04" src="https://user-images.githubusercontent.com/271363/52555760-8ba1b400-2de2-11e9-8026-41a91f04a582.png">

Eric mentioned on a call last week that ultimately, tooltips will hold description information too.

I am investigating a better solution, but don't want this sort of thing holding up the release or port to Vs4Mac.

**Comment by netonjm** [comment]
Maybe @vancura can help here too

**Comment by vancura** [comment]
This was designed as the first thing ever:

![image](https://user-images.githubusercontent.com/4982/52561109-ba2b8900-2dfa-11e9-92fe-02d8f7c6b7ca.png)

**Comment by alanmcgovern** [comment]
What if it's not multiline?

**Comment by alanmcgovern** [comment]
Specifically, in the XAML case we show the name of the C# property as the label. I took a quick scout for a long one and this showed up: `HorizontalScrollBarVisibility`

**Comment by vancura** [comment]
I believe we, as MSFT, should keep the voice human and not robotic (see https://medium.com/microsoft-design/microsoft-voice-principles-1-730f413190c1). This is precisely the place where we easily sound like robots. Is there a way to translate IDs like `HorizontalScrollBarVisibility` to `Horizontal scroll bar visibility:`?

**Comment by alanmcgovern** [comment]
In this scenario the name in the property panel is a 1:1 match with the name used in the C# property declaration and also the XAML file itself. This is the same behaviour as WPF/UWP.

We could create a file, or annotation, for every public property in Xamarin.Forms but it would be an expensive process.

**Comment by CartBlanche** [comment]
As per my screenshot above, the long property names are definitely not multi-line.
I think the tooltip, though not brilliantly aesthetic, can be made to only appear for properties that have been cut off (the code for that is already working). Ideally if we can reposition the tooltip's popup, so it happens right over the cut off text, then that is the kind of behaviour we have on Windows, IIRC.

**Comment by hbons** [comment]
Some macOS apps also squeeze the letter spacing when space is tight. It that a possibility?

**Comment by CartBlanche** [comment]
@hbons Could you give a visual example of this, I can't picture it right now.

**Comment by vancura** [comment]
AppKit (I think Quartz rather) tweaked tracking between letters, so for some time, it was possible to fit the label inside more and more narrow space. I investigated, and it seems the treatment is not available in Mojave anymore, instead they use ellipsis coming from the middle:

![screenflow](https://user-images.githubusercontent.com/4982/52573085-9f1c4180-2e19-11e9-87d3-e7a99ae147c2.gif)

**Comment by hbons** [comment]
boo :(

**Comment by vancura** [comment]
Yeah, it was a lovely detail. Old Apple.

**Comment by CartBlanche** [comment]
@hbons, @vancura, This still works in macOS Mohave (10.14.3) just do that with the first column in `Finder`. We used to have 2 columns, but a recent change by @ermau means that it is now just have 1 column. The only way I can think this might work, would be to detect the `NSOutline.Width` changing, and when we do that, we then do some maths and then propagate a `Width` change to also happen in the `UnfocusableTextField` control we are using. Would need to test that theory.

**Comment by vancura** [comment]
We just opened a fascinating topic here: where' the threshold between a computer and human voice when showed to the user.

Long term goal: to have LUTs with human variants, which are as well translatable (with a way to show the original API ID, as a tooltip or other way).
*Short term (affecting you): please use the IDs, don't use the ellipsis (as that would be counter-productive, the name wouldn't make sense), and make sure there's a tooltip with the whole name.*

We'll reopen this issue later, but not just for Proppy. For all our IDEs in general, and Proppy should get it for free.

**Comment by CartBlanche** [comment]
OK Tooltips it is, for now.

**Comment by netonjm** [comment]
![image](https://user-images.githubusercontent.com/1587480/58345454-b1663c80-7e58-11e9-98f8-9f59095c6731.png)


It seems that we still have this problem in the most recent master.

**Comment by BretJohnson** [comment]
And here's a worse example, in category view.

Maybe we should make the default property pad width wider?
Or the width of all the controls on the right a little narrower, at least in this scenario?

![image](https://user-images.githubusercontent.com/245892/58345596-bca07480-7e26-11e9-9ba0-dc308f896f42.png)

**Comment by CartBlanche** [comment]
@BretJohnson Currently the we are using a GoldenRation to split up the label with the editor and it keeps that ratio as you resize the editor, so as to the keep the aesthetic.

**Comment by BretJohnson** [comment]
@CartBlanche Gotcha. So on that, I noticed (now that resize is working) that when I resized to fix the clipping, it didn't really do what I wanted - that is, I had to make it pretty wide so the labels weren't clipped as much of the new space when to the right hand column.

Depending on how we solve the clipping issue otherwise, we _might_ want to change the ratio there when resizing. But let's figure out an answer to the bigger problem first.

**Comment by BretJohnson** [comment]
@CartBlanche is the clipping not a (big) problem currently for you, with the iOS Designer property editor?

**Comment by BretJohnson** [comment]
Here's another screenshot, from Android this time:

![image](https://user-images.githubusercontent.com/245892/59454119-6a2bf580-8ddf-11e9-999c-15845f733a1a.png)

Some thoughts from me on this:  I'd probably make the right column narrower, reduce the space after the colon, and make the whole property editor somewhat wider by default. Possibly even use a smaller font. And then of course also do something for exceptional cases where the labels don't fit, like use ellipses, but we'd never want them truncated by default - at least not for common cases - I would think.

Anyway, I'd like to resume the discussion with @vancura and @hbons on this when we can, to get their expert input.

**Comment by vancura** [comment]
Why can't we do the multiline treatment from https://github.com/xamarin/Xamarin.PropertyEditing/issues/486#issuecomment-462299544?

>  I'd probably make the right column narrower

This is an option, but it would break some other editors.

> reduce the space after the colon

No, please. This gap has been well designed, tested and implemented in many designs. Don't change this.

> make the whole property editor somewhat wider by default.

I am fine with this.

> Possibly even use a smaller font.

**No, no no no.** Accessibility reasons.

**Comment by BretJohnson** [comment]
@vancura On Windows the property labels are left aligned, with no colon, the same as they currently are on VSMac with the old property editor.

Is the left aligned vs right aligned label UX a platform convention, where we want to continue to have it different on VS Windows vs VS Mac? I'm just wondering what the rule/rationale is here.

![image](https://user-images.githubusercontent.com/245892/59633621-e9d8fd80-911a-11e9-9b8e-6107eb136bc5.png)

**Comment by vancura** [comment]
> If you find ellipses as better than what's happening now, let's go ahead and make that change (I believe it's relatively simple) and then we can continue to look at other options.

Yup, let's do the ellipsis, that's the easiest way now.

> Is the left aligned vs right aligned label UX a platform convention, where we want to continue to have it different on VS Windows vs VS Mac? I'm just wondering what the rule/rationale is here.

We'll eventually work on the VS property pad too. On Mac, it's normal that labels are right-aligned, left to the values/editors. And then you need the colon, as they're close to the right side.

When the labels are right-aligned (and close to the values), they're easy to read quickly.

**Comment by vancura** [comment]
One thing about the image in https://github.com/xamarin/Xamarin.PropertyEditing/issues/486#issuecomment-501804231: @ermau please, is it possible to rewrite the labels there, so only the first letter is capitalized?

**Comment by hbons** [comment]
What are the issues you are running into making a label multiline?

**Comment by vancura** [comment]
Multiline labels were the requirement we discussed when we started the project. The referenced image was designed circa two years ago, as the first detail ever. Back then, I clearly stated that we need multiline labels just because of this issue, which was the apparent issue I expected. Are there technical limitations we need to use ellipsis instead? I am just wondering why this wasn't implemented a long time ago.

**Comment by CartBlanche** [comment]
After a meeting with UX Board (@vancura was in attendance from Xamarin's side), it was agreed we'd try to implement the centre ellipsis solution, while keeping the mouse over Tooltip for those situations where even the centre ellipsis isn't readable.

**Comment by vancura** [comment]
BTW here is the bug: https://devdiv.visualstudio.com/DevDiv/_workitems/edit/952995
