### ISSUE TITLE
[Mac] Images are missing in MonoDevelop (resource missing?)

### ISSUE THREAD

**Issue by netonjm** [xamarin/Xamarin.PropertyEditing#488]
![image](https://user-images.githubusercontent.com/1587480/50037813-9247c100-0015-11e9-9198-29495b3238fd.png)

It needs some investigation but looks like the resources are not in the expected folder for some reason.

**Comment by CartBlanche** [comment]
After a chat with @netonjm This occurs because our resources are set to Bundle Resources. We'll need to change this to EmbeddedResource, unless some has another suggestion.

**Comment by alanmcgovern** [comment]
Yes - we need to embed them as we don't have an appbundle.

If we use any NSBundle based APIs to load images we will have to migrate them too :)

**Comment by ermau** [comment]
> After a chat with @netonjm This occurs because our resources are set to Bundle Resources. We'll need to change this to EmbeddedResource, unless someone has another suggestion.

This may break named NSImages, we'll need to update the default `HostResourceProvider` implementation to address the change.

**Comment by CartBlanche** [comment]
@netonjm Can I close this issue? I believe you tested and merged my PR on the VS4Mac side.

**Comment by netonjm** [comment]
Yes! now is a MD task
