### ISSUE TITLE
[Mac] PropertyEdititing API should allow to change/expose internal styling related properties 

### ISSUE THREAD

**Issue by netonjm** [xamarin/Xamarin.PropertyEditing#498]
I'm talking about:

- BackgroundColor 
- Margin/Border

![image](https://user-images.githubusercontent.com/1587480/51380824-e3663b80-1b12-11e9-95d5-01fb7447771a.png)

**Comment by ermau** [comment]
BackgroundColor is exposed through the new theming APIs. Margin is defined externally by the implementor, Padding is defined by the design.
