### ISSUE TITLE
Don't separate properties if they are all uncommon

### ISSUE THREAD

**Issue by garuma** [xamarin/Xamarin.PropertyEditing#503]
If all the property in a given group are uncommon, the UI currently displays an empty space with the expander collapsed.

It would be great if this situation is detected and no UI affordance is created to hide the properties (essentially falling back to a mode where there is no uncommon property).

The following diff does the trick locally but might not be the best solution:

``` diff
diff --git a/Xamarin.PropertyEditing/ViewModels/PanelViewModel.cs b/Xamarin.PropertyEditing/ViewModels/PanelViewModel.cs
index 25ff232..a26e51a 100644
--- a/Xamarin.PropertyEditing/ViewModels/PanelViewModel.cs
+++ b/Xamarin.PropertyEditing/ViewModels/PanelViewModel.cs
@@ -86,6 +86,10 @@ namespace Xamarin.PropertyEditing.ViewModels
 			if (editors == null)
 				throw new ArgumentNullException (nameof (editors));
 
+			// Disable separate if all editors are uncommon
+			if (separate && editors.OfType<PropertyViewModel> ().All (pvm => pvm.Property.IsUncommon))
+				separate = false;
+
 			foreach (EditorViewModel evm in editors)
 				AddCore (evm, separate);
 		}

```

**Comment by garuma** [comment]
Example in-IDE without the change:

![screen shot 2019-01-22 at 4 58 39 pm](https://user-images.githubusercontent.com/104105/51568172-1b4ce600-1e67-11e9-83d6-137e9b2a1733.png)

Equivalent but with the change:

![screen shot 2019-01-22 at 4 52 45 pm](https://user-images.githubusercontent.com/104105/51568181-2142c700-1e67-11e9-9a74-7256923b3ef2.png)

**Comment by ermau** [comment]
Unfortunately this would need a fair bit of tracking to manage it independently of the `IPropertyInfo`'s value through filtering. Semantically the property is a hint and it's up to us to present as we see fit based on that. However the real intent is simply to provide a method of curation to the target platform, so I think that's how we should treat it and have the platform implement this if that's what they want. If we come across a case where we need it as the hint we can revisit then.
