### ISSUE TITLE
[Mac][Accessibility] Press Tab in SearchTextField doesn't focus the first element of the PropertyPanel

### ISSUE THREAD

**Issue by netonjm** [xamarin/Xamarin.PropertyEditing#510]
![badfocusorder](https://user-images.githubusercontent.com/1587480/52006239-f4785a80-24cb-11e9-9065-685ccfec0fa6.gif)

**Comment by netonjm** [comment]
Maybe is needed a Window.RecalculateKeyViewLoop after generate all property views

**Comment by CartBlanche** [comment]
I tried calling `Window.RecalculateKeyViewLoop` or  setting `NextKeyView`, but neither works. May need some help it getting this one sorted.

**Comment by netonjm** [comment]
Did you check if could be related override PreviousResponder and NextResponder? Maybe the first element has no PreviousResponder or something is breaking the current Focus chain?

**Comment by CartBlanche** [comment]
@netonjm I'm back to looking at this, so will double check. I think I checked this last time and everything looked fine to me.
