### ISSUE TITLE
[Mac] Labels in categories are not eligible, it happens when we reload the property panel

### ISSUE THREAD

**Issue by netonjm** [xamarin/Xamarin.PropertyEditing#511]
It's not happening all the time, but very frequently when the property panel is in arrangle mode = Category.

Expanding and collapsing a section there is a label overlapped.

![issue-constraints](https://user-images.githubusercontent.com/1587480/52007129-21c60800-24ce-11e9-9084-65e0c4abcf78.gif)

**Comment by ermau** [comment]
This might have been addressed in #546, reopen if you can still reproduce it.
