### ISSUE TITLE
System.Collections.Generic.KeyNotFoundException refreshing properties with arrangle mode "category"

### ISSUE THREAD

**Issue by netonjm** [xamarin/Xamarin.PropertyEditing#512]
![issue-refreshing](https://user-images.githubusercontent.com/1587480/52008028-08be5680-24d0-11e9-9269-34babb50c7b0.gif)

Log details: 
https://gist.github.com/netonjm/4ce7407a084202763238a9ab46a1364a

**Comment by ermau** [comment]
What are the reproduction steps? Your gif doesn't show what actually triggers this.

**Comment by netonjm** [comment]
The problem was refreshing quickly the Properties with the NSView example arranged by category. I checked with Dominique and seems it's expected. Closing this issue.
