### ISSUE TITLE
[Mac] Property Search is no longer positioned correctly.

### ISSUE THREAD

**Issue by CartBlanche** [xamarin/Xamarin.PropertyEditing#515]
As per screenshot...
<img width="656" alt="screen shot 2019-02-01 at 20 57 27" src="https://user-images.githubusercontent.com/271363/52149283-1e648500-2664-11e9-9492-159f29cd8259.png">

**Comment by ermau** [comment]
Do you mean the placeholder? The search itself is placed correctly.

**Comment by CartBlanche** [comment]
@ermau The width and spacing from the right is not what it was previously.

**Comment by ermau** [comment]
It wasn't correct to begin with.
