### ISSUE TITLE
[Mac] Arrange toolbar is not selecting (Focus Ring) the elements on click

### ISSUE THREAD

**Issue by netonjm** [xamarin/Xamarin.PropertyEditing#523]
The focus ring must select the element when clicked

![proppy-issue](https://user-images.githubusercontent.com/1587480/52476451-f662ad80-2b9e-11e9-80c0-e09c0d268384.gif)

**Comment by CartBlanche** [comment]
The category and A…Z buttons are image buttons, not regular buttons, so they will not have focus rectangles, only the select underline, as seen in your video. Once you merge my PR, you will see the images there.

**Comment by netonjm** [comment]
Right, seems it works only from keyboard, not click, so closing the issue 👍
