### ISSUE TITLE
VSTS - Error generating the MD bundle (Duplicated resources)

### ISSUE THREAD

**Issue by netonjm** [xamarin/Xamarin.PropertyEditing#566]
Only for the logs:

We have some problems trying to generate the bundle for monodevelop rebasing to most recent version of proppy.

The problem is we have dupplicated the respources in the bundle.

**Comment by alanmcgovern** [comment]
https://github.com/xamarin/md-addins/commit/59f0390d639f2ce053f87aac3042dbd85c8dfa28
