### ISSUE TITLE
Move ViewDidChangeEffectiveAppearance calls

### ISSUE THREAD

**Issue by ermau** [xamarin/Xamarin.PropertyEditing#587]
We need to move our effective appearance calls to a second method that we can call from the ctor and an override.

**Comment by CartBlanche** [comment]
@ermau I see how this will fix the immediate bug of ViewDidChangeEffectiveAppearance being called on OSes that don't have that call, but how will we notify the views of an Appearance change on those older OSes? AFAICT, the previous mechanism has been removed.

**Comment by ermau** [comment]
It won't, we can't support live theme changes on prior OS

**Comment by CartBlanche** [comment]
@ermau couldn't we have had a system that fell back to the previous (or better version of) mechanism on prior OSes, and uses the new one on OSes that support it?
