### ISSUE TITLE
Define property to enable Xamarin.Mac API analysis in the IDE

### ISSUE THREAD

**Issue by Therzok** [xamarin/Xamarin.PropertyEditing#599]
Over at monodevelop we have included a new MSBuild property that's included in the project. This is used to enable Xamarin.Mac API availability analyzers in the source code.

Details on how here: https://github.com/mono/monodevelop/commit/5c5a62cd789bcf0723445af21f6fb080c6747b41

**Comment by CartBlanche** [comment]
@Therzok Just to be 100% sure, we need to add https://github.com/mono/monodevelop/commit/5c5a62cd789bcf0723445af21f6fb080c6747b41#diff-1f3462f1373425a15290625aac5dcb5fR61 to our proppy project files?

**Comment by Therzok** [comment]
Yes, that's all you need. We target 10.12 now, so just add `<XamarinMacAnalyzerMinimumOSVersion>10.12</XamarinMacAnalyzerMinimumOSVersion>`. That should flag API usages for APIs not available in the deployment target.
