### ISSUE TITLE
[Mac] PropertyButton doesn't handle reuse correctly.

### ISSUE THREAD

**Issue by CartBlanche** [xamarin/Xamarin.PropertyEditing#606]
As such if the VM changes it wouldn't repopulate the context menu correctly.

**Comment by CartBlanche** [comment]
@ermau If the VM changes and we clear down the popup menu list and reset it. I think that should give us what we need. 

`internal PropertyViewModel ViewModel
		{
			get { return this.viewModel; }
			set {
				if (this.viewModel != null) {
					this.viewModel.PropertyChanged -= OnPropertyChanged;
				}

				this.viewModel = value;

				if (this.viewModel != null) {
					this.viewModel.PropertyChanged += OnPropertyChanged;
					ValueSourceChanged (this.viewModel.ValueSource);
				}

				if (this.popUpContextMenu != null) {
					this.popUpContextMenu.RemoveAllItems ();
					this.popUpContextMenu = null;
				}
			}
		}`

**Comment by ermau** [comment]
Fixed in #608
