### ISSUE TITLE
Mac name object

### ISSUE THREAD

**Issue by ermau** [xamarin/Xamarin.PropertyEditing#87]
- [x] Design
 - [x] VM
 - [x] Host implementation

**Comment by vancura** [comment]
There's no _Windows Name Object_. Correct?

**Comment by ermau** [comment]
Correct, but there is an equivalent, it just happens to already be completed.

**Comment by vancura** [comment]
## Light theme:

<img width="408" alt="ios designer name object 2x" src="https://user-images.githubusercontent.com/4982/35621897-4a77315a-0686-11e8-9601-3b696ceac643.png">

## Dark theme:

<img width="408" alt="ios designer name object dark 2x" src="https://user-images.githubusercontent.com/4982/35621901-51b66558-0686-11e8-95ff-ef7aa3d0325e.png">

Thoughts?

**Comment by ermau** [comment]
@vancura Does this header scroll out of the way? When I enter a filter is it removed?

**Comment by vancura** [comment]
I'd say it scrolls out of the way (it's not sticky), and it's displayed only when not filtering (filtering hides it and shows filtered results).

**Comment by CartBlanche** [comment]
@ermau The Name object looks like just a string field? I noticed the VM checkbox is ticked. Is it called something specific (which I can't find) or are you referring to using PropertyViewModel<string> for it?

**Comment by ermau** [comment]
@CartBlanche https://github.com/xamarin/Xamarin.PropertyEditing/blob/master/Xamarin.PropertyEditing/ViewModels/PropertiesViewModel.cs#L62-L87
