### ISSUE TITLE
Mac Group Editor

### ISSUE THREAD

**Issue by ermau** [xamarin/Xamarin.PropertyEditing#97]
- Core:
   - [x] View Model
   - [x] Tests
 - Editor:
   - [ ] Design
   - [ ] Localized
   - Behavior:
     - [ ] Keyboard control
     - [ ] Accessibility
     - [ ] Selection
   - Theming:
     - [ ] Light themed
     - [ ] Dark themed
     - [ ] High contrast

**Comment by vancura** [comment]
There's no _Windows Group Editor_ filed, correct?

**Comment by ermau** [comment]
It's already been completed.

**Comment by lewing** [comment]
So I've done some exploratory work here and I'm not confident that controls spanning multiple columns (as per the design mockups) will actually work well in NSOutlineView.  Is there any functioning prior art for this?

**Comment by ermau** [comment]
Not on Mac, it's possible we need to move away from columns and instead layout the label ourselves.
